import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "./components/react-query-client-provider";
import { AppointmentSelectorProvider } from "./components/appointment-selector-provider";
import { Header } from "./components/header";
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-zinc-50">
      <ReactQueryClientProvider>
        <AppointmentSelectorProvider>
          <body>
            <Header />
            <main className="px-8 md:px-24 py-8 bg-zinc-50">{children}</main>
            <Toaster />
          </body>
        </AppointmentSelectorProvider>
      </ReactQueryClientProvider>
    </html>
  );
}
